### PR TITLE
Faster block loading times

### PR DESCRIPTION
**Pull request by ghobson2013**
Hi FreeTrade,

Created new AES cache to hold block headers for faster startup. The first time you pay the same penalty to load the block index as it builds the header cache and verify's their authenticity , once that is done a subsequent load is much faster. 
My testing shows going from 250s down to 5s. ( at the expense of about 26Mb of disk space for the cache). The code takes over 50% of the UTXO reserved space for this cache.
This needs more testing on multiple platforms, but looks promising so far, its up to you to decide to accept/deny this pull request.

### CODE REVIEW

**Comment by FreeTrade** [comment]
Wow. Checking it out now. Any idea what's going on with the Apple build failing on Travis - is that a timeout or another error?

**Comment by FreeTrade** [comment]
Yep, really nice. Very fast start now with the cache. :)

**Comment by ILayZ** [comment]
@FreeTrade When this feature will appear in win-build?

**Comment by ghobson2013** [comment]
the travis error is most likely due to a missing asset, probably a library or tarball its trying to download that is no longer available.

**Pull request merged**
